import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "secondary-dim": "#9547f7",
        "surface-tint": "#97a9ff",
        "error": "#ff6e84",
        "secondary-fixed-dim": "#d6b6ff",
        "on-tertiary": "#006165",
        "surface-container-lowest": "#000000",
        "inverse-surface": "#fcf8ff",
        "on-primary": "#002283",
        "on-secondary": "#2f0060",
        "on-primary-fixed-variant": "#00207e",
        "tertiary-dim": "#00e5ee",
        "on-surface": "#e5e2ff",
        "surface": "#0a082f",
        "on-secondary-container": "#ebd8ff",
        "error-dim": "#d73357",
        "surface-bright": "#26245f",
        "on-error": "#490013",
        "tertiary-container": "#00f4fe",
        "tertiary-fixed-dim": "#00e5ee",
        "on-tertiary-container": "#00575b",
        "primary-fixed": "#859aff",
        "inverse-on-surface": "#52517a",
        "surface-container-highest": "#201e55",
        "outline": "#72719c",
        "surface-dim": "#0a082f",
        "tertiary": "#a1faff",
        "inverse-primary": "#134af1",
        "tertiary-fixed": "#00f4fe",
        "error-container": "#a70138",
        "on-surface-variant": "#a8a7d5",
        "on-background": "#e5e2ff",
        "on-secondary-fixed-variant": "#6f08d0",
        "primary": "#97a9ff",
        "secondary-fixed": "#e1c7ff",
        "surface-container": "#151341",
        "surface-variant": "#201e55",
        "primary-container": "#859aff",
        "on-tertiary-fixed-variant": "#006266",
        "secondary-container": "#6e06d0",
        "primary-dim": "#3e65ff",
        "surface-container-high": "#1a194b",
        "primary-fixed-dim": "#718bff",
        "background": "#0a082f",
        "surface-container-low": "#0f0d38",
        "outline-variant": "#45446c",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed": "#4a0090",
        "on-primary-container": "#001867",
        "on-tertiary-fixed": "#004346",
        "secondary": "#b884ff",
        "on-error-container": "#ffb2b9"
      },
      fontFamily: {
        headline: ["Manrope"],
        body: ["Inter"],
        label: ["Inter"],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.2' }],
        '6xl': ['3.75rem', { lineHeight: '1.1' }],
      },
      spacing: {
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
        40: '10rem',
        48: '12rem',
        56: '14rem',
        64: '16rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      transitionDuration: {
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'pulse-soft': 'pulseSoft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
