import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Light, high-contrast palette. Token names are kept so existing pages switch theme without renames.
        "background": "#fbfbfe",
        "surface": "#fbfbfe",
        "surface-dim": "#f1f2f8",
        "surface-bright": "#ffffff",
        "surface-tint": "#4f46e5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f5fb",
        "surface-container": "#ffffff",
        "surface-container-high": "#eef0f8",
        "surface-container-highest": "#e5e8f3",
        "surface-variant": "#eef0f8",
        "on-surface": "#0f1233",
        "on-background": "#0f1233",
        "on-surface-variant": "#4b5072",
        "inverse-surface": "#0f1233",
        "inverse-on-surface": "#eef0ff",
        "outline": "#7d82a8",
        "outline-variant": "#d7daea",
        "ink": "#0b0d2a",
        "ink-soft": "#171a45",
        "primary": "#4f46e5",
        "primary-dim": "#4338ca",
        "primary-fixed": "#818cf8",
        "primary-fixed-dim": "#6366f1",
        "primary-container": "#e0e7ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#312e81",
        "on-primary-fixed": "#1e1b4b",
        "on-primary-fixed-variant": "#3730a3",
        "inverse-primary": "#a5b4fc",
        "secondary": "#7c3aed",
        "secondary-dim": "#6d28d9",
        "secondary-container": "#6d28d9",
        "secondary-fixed": "#ede9fe",
        "secondary-fixed-dim": "#ddd6fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#ffffff",
        "on-secondary-fixed": "#4c1d95",
        "on-secondary-fixed-variant": "#5b21b6",
        "tertiary": "#0891b2",
        "tertiary-dim": "#0e7490",
        "tertiary-container": "#cffafe",
        "tertiary-fixed": "#a5f3fc",
        "tertiary-fixed-dim": "#67e8f9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#155e75",
        "on-tertiary-fixed": "#083344",
        "on-tertiary-fixed-variant": "#155e75",
        "success": "#059669",
        "error": "#dc2626",
        "error-dim": "#b91c1c",
        "error-container": "#fee2e2",
        "on-error": "#ffffff",
        "on-error-container": "#7f1d1d"
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.2' }],
        '6xl': ['3.75rem', { lineHeight: '1.1' }],
      },
      spacing: {
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
        40: '10rem',
        48: '12rem',
        56: '14rem',
        64: '16rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      transitionDuration: {
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'pulse-soft': 'pulseSoft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
