import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Dark, high-contrast palette. Token names are kept so existing pages switch theme without renames.
        "background": "#070918",
        "surface": "#070918",
        "surface-dim": "#04050f",
        "surface-bright": "#1a1e4d",
        "surface-tint": "#818cf8",
        "surface-container-lowest": "#04050f",
        "surface-container-low": "#0b0e25",
        "surface-container": "#111437",
        "surface-container-high": "#181c47",
        "surface-container-highest": "#20255a",
        "surface-variant": "#181c47",
        "on-surface": "#eef0ff",
        "on-background": "#eef0ff",
        "on-surface-variant": "#b3b8dc",
        "inverse-surface": "#eef0ff",
        "inverse-on-surface": "#0f1233",
        "outline": "#8f95c6",
        "outline-variant": "#272c60",
        "ink": "#151a55",
        "ink-soft": "#1e2366",
        "primary": "#4f46e5",
        "primary-dim": "#4338ca",
        "primary-fixed": "#a5b4fc",
        "primary-fixed-dim": "#818cf8",
        "primary-container": "#25286b",
        "on-primary": "#ffffff",
        "on-primary-container": "#e0e7ff",
        "on-primary-fixed": "#1e1b4b",
        "on-primary-fixed-variant": "#3730a3",
        "inverse-primary": "#4f46e5",
        "secondary": "#7c3aed",
        "secondary-dim": "#6d28d9",
        "secondary-container": "#6d28d9",
        "secondary-fixed": "#2e1065",
        "secondary-fixed-dim": "#c4b5fd",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#ffffff",
        "on-secondary-fixed": "#ede9fe",
        "on-secondary-fixed-variant": "#5b21b6",
        "tertiary": "#0891b2",
        "tertiary-dim": "#0e7490",
        "tertiary-container": "#083344",
        "tertiary-fixed": "#a5f3fc",
        "tertiary-fixed-dim": "#67e8f9",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#a5f3fc",
        "on-tertiary-fixed": "#083344",
        "on-tertiary-fixed-variant": "#155e75",
        "success": "#34d399",
        "error": "#f87171",
        "error-dim": "#ef4444",
        "error-container": "#3b1219",
        "on-error": "#ffffff",
        "on-error-container": "#fecaca"
      },
      fontFamily: {
        headline: ["var(--font-manrope)", "Manrope", "system-ui", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        xs: ['0.75rem', { lineHeight: '1rem' }],
        sm: ['0.875rem', { lineHeight: '1.25rem' }],
        base: ['1rem', { lineHeight: '1.5rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.2' }],
        '6xl': ['3.75rem', { lineHeight: '1.1' }],
      },
      spacing: {
        0: '0',
        1: '0.25rem',
        2: '0.5rem',
        3: '0.75rem',
        4: '1rem',
        6: '1.5rem',
        8: '2rem',
        10: '2.5rem',
        12: '3rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        32: '8rem',
        40: '10rem',
        48: '12rem',
        56: '14rem',
        64: '16rem',
      },
      borderRadius: {
        none: '0',
        sm: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
      },
      transitionDuration: {
        150: '150ms',
        200: '200ms',
        300: '300ms',
        500: '500ms',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'pulse-soft': 'pulseSoft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
