import Link from 'next/link';
import { ArrowRight, Calculator, FileText, HardDrive } from 'lucide-react';
import { CTABanner } from './CTABanner';

export function Phase2TurkishCaseStudies() {
  return <>
    <section className="bg-gradient-to-br from-surface via-surface-container-low to-primary/10 py-16 md:py-24"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><nav aria-label="Breadcrumb" className="mb-8 text-sm text-on-surface-variant"><Link href="/tr">Ana Sayfa</Link><span className="mx-2">/</span><span>Vaka Çalışmaları</span></nav><h1 className="mb-6 text-4xl font-bold md:text-5xl">Gerçek Otomasyon Vaka Çalışmaları</h1><p className="max-w-3xl text-lg leading-relaxed text-on-surface-variant">Bu sayfadaki gerçek vaka sonuçları, şirket tarafından sağlanan kaynaklarda belgelenmiş ve müşteri adı kullanılmadan yayımlanmıştır. Örnek senaryolar ayrı bölümde açıkça etiketlenir.</p></div></section>

    <section className="bg-surface py-16 md:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><h2 className="mb-10 text-3xl font-bold md:text-4xl">Gerçek Vaka Çalışmaları</h2><div className="space-y-8">
      <article className="rounded-3xl border border-primary/30 bg-surface-container p-7 md:p-10"><div className="mb-6 flex items-center gap-4"><Calculator className="text-primary" size={34} /><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Anonimleştirilmiş gerçek vaka · İnsan Kaynakları</p><h3 className="mt-2 text-2xl font-bold">KPI Prim Hesaplama Süreci Otomasyonu</h3></div></div><div className="grid gap-8 md:grid-cols-2"><div className="space-y-4 leading-relaxed text-on-surface-variant"><p>İnsan kaynakları çalışanları KPI prim hesaplaması için birden fazla kurumsal sistemden veri topluyor ve Excel tabanlı manuel işleme adımları yürütüyordu.</p><p>Başlangıçta süreçte 8 çalışan görev alıyor ve hesaplama döngüsü yaklaşık 20 gün sürüyordu. Otomasyon sonrasında sürece dahil olan çalışan sayısı 1’e, işlem süresi 3 güne indi.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-primary/10 p-6"><p className="text-4xl font-bold text-primary">8 → 1</p><p className="mt-2">Sürece dahil olan çalışan sayısı</p></div><div className="rounded-2xl bg-primary/10 p-6"><p className="text-4xl font-bold text-primary">20 → 3 gün</p><p className="mt-2">KPI prim hesaplama süresi</p></div></div></div></article>
      <article className="rounded-3xl border border-primary/30 bg-surface-container p-7 md:p-10"><div className="mb-6 flex items-center gap-4"><FileText className="text-primary" size={34} /><div><p className="text-sm font-semibold uppercase tracking-wider text-primary">Anonimleştirilmiş gerçek vaka · Muhasebe / Finans</p><h3 className="mt-2 text-2xl font-bold">Belge İşleme ve Muhasebe Otomasyonu</h3></div></div><div className="grid gap-8 md:grid-cols-2"><div className="space-y-4 leading-relaxed text-on-surface-variant"><p>Muhasebe ve birincil belgelerin manuel kaydı önemli çalışan eforu gerektiriyor ve manuel veri girişi hatası olasılığı oluşturuyordu.</p><p>Otomatik süreç; tarama, fotoğraf, e-posta veya paylaşılan kaynaktan belge alıyor; bilgiyi tanıyor, çıkarıyor ve doğruluyor; muhasebe sistemi verisiyle karşılaştırıyor, gerekli kontrolleri yapıyor ve kaydı oluşturuyordu.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-primary/10 p-6"><p className="text-4xl font-bold text-primary">3–20x</p><p className="mt-2">Belge kayıt işinde daha düşük iş gücü gereksinimi</p></div><div className="rounded-2xl bg-primary/10 p-6"><p className="text-4xl font-bold text-primary">2–3x</p><p className="mt-2">Gelen belge işleme hızında artış</p></div></div></div></article>
    </div><p className="mt-7 text-sm text-on-surface-variant">Sonuçlar ilgili vaka çalışmalarına aittir. Her sürecin otomasyon potansiyeli mevcut sistemlere ve süreç yapısına göre değişebilir.</p></div></section>

    <section className="bg-surface-container-low py-16 md:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8"><h2 className="mb-5 text-3xl font-bold md:text-4xl">Otomasyon Senaryoları</h2><p className="mb-9 max-w-3xl text-on-surface-variant">Aşağıdaki içerik müşteri projesi veya ölçülmüş sonuç değildir. Şirket materyallerinde tasarlanmış SAP kullanım alanlarının özetidir.</p><article className="rounded-2xl border border-outline/20 bg-surface-container p-7"><div className="mb-4 flex items-center gap-3"><HardDrive className="text-primary" /><p className="text-sm font-semibold uppercase tracking-wider text-primary">Örnek otomasyon senaryosu</p></div><h3 className="mb-4 text-2xl font-bold">SAP Kontrol ve Mutabakat Senaryoları</h3><p className="mb-5 leading-relaxed text-on-surface-variant">Amortisman kontrolü, birincil belge sürelerinin izlenmesi, vergi ve amortisman parametrelerinin kontrolü, gayrimenkul ve kadastro verisi karşılaştırması, tutarsızlık raporu oluşturma ve sonuçları sorumlu çalışanlara gönderme adımları.</p><Link href="/tr/sap-otomasyonu" className="inline-flex items-center gap-2 font-semibold text-primary">SAP otomasyonunu inceleyin <ArrowRight size={17} /></Link></article></div></section>
    <section className="bg-surface py-16"><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><CTABanner heading="Benzer Bir Süreci Birlikte Değerlendirelim" description="Vaka sonuçları her süreç için garanti değildir. Mevcut sistemleri ve iş akışını inceleyerek uygun otomasyon kapsamını belirleyelim." primaryCTA={{ text: 'Demo Talep Edin', href: '/tr/contact' }} /></div></section>
  </>;
}
